### ISSUE TITLE
[Un]intended build dependency on clang 10?

### ISSUE THREAD

**Issue by hanno-becker** [fortanix/rust-mbedtls#105]
When trying to build the crate out of the box, I run into the following:

```
     Running `rust-mbedtls/target/debug/build/mbedtls-sys-auto-73e3f3822172cf1c/build-script-build`
[mbedtls-sys-auto 2.18.5] rust-mbedtls/target/debug/build/mbedtls-sys-auto-73e3f3822172cf1c/
build-script-build: error while loading shared libraries: libclang.so.10svn: cannot open shared object file: No such file or directory

error: failed to run custom build command for `mbedtls-sys-auto v2.18.5 (rust-mbedtls/mbedtls-sys)`
```

Is the dependency on Clang 10 (released end of March 2020) expected?

**Comment by jethrogb** [comment]
Not sure how this happens. We only use LLVM 3.8 ourselves, so I don't think this is something we do conciously.

**Comment by ndokmai** [comment]
Is it possible that you somehow have Clang 10 installed or configured in your system? If you export [these environment variables](https://github.com/KyleMayes/clang-sys#environment-variables) and LD_LIBRARY_PATH to a different clang library and binaries (make sure to clean and rebuild), does the error go away?
