### ISSUE TITLE
Building for x86_64-unknown-linux-gnu fails

### ISSUE THREAD

**Issue by Goirad** [fortanix/rust-mbedtls#113]
`cargo build` on an `x86_64-unknown-linux-gnu` target works correctly, but running `cargo build --target x86_64-unknown-linux-gnu` causes the following error:

```
/home/dario/.cargo/registry/src/github.com-1ecc6299db9ec823/mbedtls-sys-auto-2.18.4/vendor/crypto/library/aes.c:31:10: fatal error: '/home/dario/work/roche/server/target/x86_64-unknown-1-gnu/debug/build/mbedtls-sys-auto-9b28b4beb79db467/out/config.h' file not found
#include MBEDTLS_CONFIG_FILE
         ^
<command line>:1:29: note: expanded from here
#define MBEDTLS_CONFIG_FILE </home/dario/work/roche/server/target/x86_64-unknown-linux-gnu/debug/build/mbedtls-sys-auto-9b28b4beb79db467/out/config.h>
```
In particular, it tries to include a file from a `x86_64-unknown-1-gnu` target for some reason.
What is especially strange is that the error helpfully shows that the definition being expanded is in fact correct.

**Comment by jethrogb** [comment]
Something to do with the C compiler. The invocation of `cc` is correct...

**Comment by jethrogb** [comment]
running with `-E` I'm seeing at least the following defines:
```
#define linux 1
#define __unix 1
#define __unix__ 1
#define unix 1
#define __ELF__ 1
#define __DECIMAL_BID_FORMAT__ 1
# 1 "<command-line>"
#define MBEDTLS_CONFIG_FILE </home/jethro/projects/public/rust-mbedtls/target/x86_64-unknown-linux-gnu/debug/build/mbedtls-sys-auto-dec3995c40e6197f/out/config.h>
```

**Comment by jethrogb** [comment]
I think we can probably switch from `#include <...>` to `#include "..."` and it should work?

**Comment by jethrogb** [comment]
I'm probably using `<...>` because double quotes can be problematic when passed on the command line
