### ISSUE TITLE
Build fails with bindgen errors

### ISSUE THREAD

**Issue by connorcl** [fortanix/rust-mbedtls#121]
I've been trying to use this library in a `no_std` project, but the build of `mbedtls-sys-auto` always fails with a large number of Bindgen ERROR: unsupported type \`CXTypeKind(119)\` errors. I tried to make sure it wasn't the result of cross-compilation or a wrong selection of features by trying to include `mbedtls` as a dependency in an otherwise empty project (not `no_std`), but the build still fails with this same bindgen error.

**Comment by jethrogb** [comment]
Duplicate of #5

**Comment by jethrogb** [comment]
Final PR: #152

**Comment by jethrogb** [comment]
Fixed in #152
