### ISSUE TITLE
Does PSA Crypto belong in this crate

### ISSUE THREAD

**Issue by mcr** [fortanix/rust-mbedtls#164]
The PSA API https://armmbed.github.io/mbed-crypto/html/about.html is implemented by mbedtls.
As far as I can see (I might have missed stuff), the mbedtls-auto-sys module is *not* wrapping the psa_* functions, but rather the underlying mbedtls functions.  If this is wrong, and I've missed stuff, please say so.
If I'm right, then I guess I need to understand how to make bindgen do it's thing.

**Comment by mcr** [comment]
Okay, I now found: 
https://github.com/fortanix/rust-mbedtls/blob/master/mbedtls-sys/build/headers.rs#L21

~~~~
      grep '^#include' *|grep -v '<'|grep -v MBEDTLS_|sed 's/:#include//;s/"//g'|sed 's#mbedtls/##g'| egrep -v ' (psa/crypto.h|psa/crypto_config.h|everest/everest.h|zlib.h|.*_alt.h)$
~~~~

so, it appears that psa/crypto.h has been explicitely excluded.  Is there a reason for that?

**Comment by mcr** [comment]
I found: https://github.com/parallaxsecond/rust-psa-crypto/tree/HEAD/psa-crypto and https://docs.rs/psa-crypto/0.9.0/psa_crypto/

**Comment by Taowyoo** [comment]
PSA is more heavily used in mbedtls 3.X, but because of https://github.com/fortanix/rust-mbedtls/issues/320, we are not planning to add/export PSA API in `mbedtls-sys`
