### ISSUE TITLE
cipher.encrypt requires an excessive buffer for PKCS#7 padding.

### ISSUE THREAD

**Issue by kitanic** [fortanix/rust-mbedtls#184]
PKCS#7 padding aligns plain data to block size. 
Therefore, for a 16-byte block, the output result will be 16, 32, 48... whichever closest boundary size to the input.

However, the following code will result in CipherFullBlockExpected error.

    let input: [u8; 47] = [0; 47];
    let mut output: [u8; 48] = [0; 48];
    let r = cipher.encrypt(&input, &mut output)?;

The following case is ok.

    let input: [u8; 47] = [0; 47];
    let mut output: [u8; 47+16] = [0; 47+16];
    let r = cipher.encrypt(&input, &mut output)?;

So it seems that it simply adds up the block size regardless of the input length. 

I can truncate result by the size of Result as a workaround, but this is an unnecessary process.

**Comment by kitanic** [comment]
I found one more erroneous behavior about PKCS#7.

The decrypted result with padding should always be smaller than the ciphertext, but the storage buffer requires the size of the ciphertext + 16bytes.
The following code will result in error.

    fn decode_test(ciphertext: &[u8], key: &[u8], iv: &[u8]) {
      let mut plain = Vec::new();

      plain.resize(ciphertext.len(), 0); // MUST: plain < cipher
 
      let mut cipher = Cipher::<Decryption, Traditional>::new(CipherId::Aes, CipherMode::CBC, (key.len() as u32) * 8)?;
      cipher.set_padding(CipherPadding::Pkcs7)?;
      let cipher = cipher.set_key_iv(key, iv)?;

      cipher.decrypt(ciphertext, &mut plain)?; // An error occurred here.
    }

**Comment by jethrogb** [comment]
This requirement comes from MbedTLS

> `output` The buffer for the output data. This must be able to hold at least `ilen + block_size`. This must not be the same buffer as `input`.

https://tls.mbed.org/api/cipher_8h.html#a1c249f6ee1a0d2c906927c7790c41dc5

**Comment by kitanic** [comment]
No. It is incorrect.

In practice, it don't need more buffer than necessary, and it can encrypt without any problem if you have enough space for *just* blocksize boundary.
Perhaps the mbedtls documentation is wrong(!). 

This is verification code.
[check.c.txt](https://github.com/fortanix/rust-mbedtls/files/8060367/check.c.txt)

**Comment by jethrogb** [comment]
I understand that logically in some cases not the full output buffer is accessed, but for memory safety we must follow the documented API. We can relax the requirements in the bindings if MbedTLS does.

**Comment by kitanic** [comment]
I agree it.
So my suggestion is to not do a prior buffer size check in the rust side implementation. mbedtls should receive olen during encryption/decryption to check for buffer size and return MBEDTLS_ERR_CIPHER_FULL_BLOCK_EXPECTED if necessary. Therefore, there is no risk of crashing if you pass an undersized buffer.

Wrappers should not limit native behavior, and should follow its error codes.
