### ISSUE TITLE
Any ETA for Crate Update

### ISSUE THREAD

**Issue by kedars** [fortanix/rust-mbedtls#196]
Hi, it's been a while since the crate is updated on https://crates.io/crates/mbedtls, any ETA for when an update is planned? 

I wish to publish a crate that depends on rust-mbedtls, and it appears I can't publish it with dependencies referring to git repositories.

**Comment by zugzwang** [comment]
Hello @kedars, thanks for reaching out and your contributions. Please allow some more time, as we are doing clean-up currently.
