### ISSUE TITLE
How to build TCP + TLS client using mbedtls in no_std env?

### ISSUE THREAD

**Issue by yaoxin1995** [fortanix/rust-mbedtls#233]
Hey, I looked examples provided in this crate. 
For example : 
1. [sample client](https://github.com/fortanix/rust-mbedtls/blob/master/mbedtls/examples/client.rs) 
2. [client_server](https://github.com/fortanix/rust-mbedtls/blob/master/mbedtls/tests/client_server.rs) 

But I didn't find any example of how to use this crate to build a TCP client in no-std environment.

Do we have any example of how to build a TCP + tls client using this crate in `no-std` environment?

My assumption is that I need to implement [IoCallback](https://github.com/fortanix/rust-mbedtls/blob/master/mbedtls/tests/client_server.rs#L39)  to make the crate work in no_std, But I am not sure.

Another question: could `mbedtls` reexports [mbedtls-sys](https://github.com/fortanix/rust-mbedtls/tree/master/mbedtls-sys) publicly?

Currently, I have to add `mbedtls-sys` to my project using `mbedtls-sys-auto  = { version = "2.28.0", default-features = false}`  in order to implement the `IoCallback`  traint.   In this case, I got following error:
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
make[1]: Leaving directory '/home/yaoxin/master-thesis-quark/qvisor'
make -C ./qkernel debug
make[1]: Entering directory '/home/yaoxin/master-thesis-quark/qkernel'
RUSTFLAGS="--cfg aes_force_soft --cfg polyval_force_soft" CARGO_TARGET_DIR=../target cargo xbuild --target x86_64-qkernel.json
error: cargo metadata invocation failed: Error during execution of `cargo metadata`:     Updating crates.io index
error: failed to select a version for `mbedtls-sys-auto`.
    ... required by package `mbedtls v0.9.0 (https://github.com/fortanix/rust-mbedtls.git#4029adbc)`
    ... which satisfies git dependency `mbedtls` (locked to 0.9.0) of package `qkernel v0.6.0 (/home/yaoxin/master-thesis-quark/qkernel)`
versions that meet the requirements `^2.25.0` (locked to 2.28.0) are: 2.28.0

the package `mbedtls-sys-auto` links to the native library `mbedtls`, but it conflicts with a previous package which links to `mbedtls` as well:
package `mbedtls-sys-auto v2.28.0`
    ... which satisfies dependency `mbedtls-sys-auto = "^2.28.0"` of package `qkernel v0.6.0 (/home/yaoxin/master-thesis-quark/qkernel)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the links ='mbedtls-sys-auto' value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.

failed to select a version for `mbedtls-sys-auto` which could resolve this conflict

make[1]: *** [makefile:31: kernel_debug] Error 1
make[1]: Leaving directory '/home/yaoxin/master-thesis-quark/qkernel'
make: *** [makefile:9: debug] Error 2
```

Could you give me a hand? Many thanks

**Comment by jethrogb** [comment]
How are you planning to do TCP without std? Yes you need to provide your own IoCallback.
