### ISSUE TITLE
Fix license specification, to support cargo deny and cargo about

### ISSUE THREAD

**Issue by cbeck88** [fortanix/rust-mbedtls#240]
Many people are now using `cargo deny` to keep track of what licenses are in their dependency tree:

Currently, `mbedtls` crate has `Apache-2.0/GPL-2.0+` listed as its license in `Cargo.toml`.

However, this is not a valid SPDX expression anymore -- `GPL-2.0+` was deprecated in favor of `GPL-2.0-or-later`, in the latest versions of the spec.

https://spdx.org/licenses/

This results in errors with `cargo deny`:

```
error[unlicensed]: mbedtls = 0.8.1 is unlicensed
  ┌─ mbedtls 0.8.1
  │
2 │ name = "mbedtls"
  │         ^^^^^^^ a valid license expression could not be retrieved for the crate
3 │ version = "0.8.1"
4 │ license = "Apache-2.0 OR GPL-2.0+"
  │                                 - a GNU license was followed by a `+`
```

---

Suggestion: Change this to `Apache-2.0/GPL-2.0-or-later` to be help automated tools and downstream users

**Comment by Taowyoo** [comment]
Fixed by https://github.com/fortanix/rust-mbedtls/pull/263
