### ISSUE TITLE
Pk::len() aligns to bytes

### ISSUE THREAD

**Issue by zugzwang** [fortanix/rust-mbedtls#242]
The documentation for `Pk::len()` says "Key length in bits". However, it aligns to bytes:

```
fn main() {
    let mut entropy = mbedtls::rng::OsEntropy::new();
    let mut rng = mbedtls::rng::CtrDrbg::new(Arc::new(entropy), None).unwrap();
    let pk = Pk::generate_rsa(&mut rng, 1026, 3).unwrap();
    assert_eq!(pk.len(), pk.rsa_public_modulus().unwrap().bit_length().unwrap());
}
```

Fails to assert with `left: 1032, right: 1026`. 

This comes from MbedTLS, we should update the documentation.

**Comment by jethrogb** [comment]
Known upstream bug https://github.com/Mbed-TLS/mbedtls/issues/868
