### ISSUE TITLE
Upgrade to Mbedtls 2.28.3

### ISSUE THREAD

**Issue by DrTobe** [fortanix/rust-mbedtls#272]
In the discussion to https://github.com/fortanix/rust-mbedtls/pull/258 we agreed that we might try an upgrade to mbedtls 2.28.3 to fix builds on recent clang versions (the fix is introduced with 2.28.3). Currently, we are on version 2.28.0 from december 2021. The upgrade will additionally give us the security updates of 2.28.1 and 2.28.2. It will hopefully be easier than the upgrade to e.g. mbedtls 3.4.0 which is already ongoing, see https://github.com/fortanix/rust-mbedtls/issues/261.

@Taowyoo Will you find the time to do the upgrade soon or should I give it a try?

**Comment by Taowyoo** [comment]
Hi @DrTobe, thank you for bringing this issue to our attention.
Currently, I am occupied with the ongoing work on #261, so it might be more feasible for you to give the upgrade a try.
Let me know if you need any assistance or have any questions along the way.
