### ISSUE TITLE
allow ambiguous_glob_reexports property since rustc 1.70

### ISSUE THREAD

**Issue by mkaynov** [fortanix/rust-mbedtls#277]
rustc 1.70 denies ambiguous_glob_reexports, thus:

1. add config flag for Error enum variants export in _error.rs_  `#[allow(ambiguous_glob_reexports)]` (supported since 1.70)
2. remove env variable from CI script `export RUSTFLAGS="-A ambiguous_glob_reexports"`

https://github.com/fortanix/rust-mbedtls/pull/271#discussion_r1217952246

apply not earlier than November 2023

**Comment by Taowyoo** [comment]
Done by https://github.com/fortanix/rust-mbedtls/pull/278
