### ISSUE TITLE
Link error on M1 Mac

### ISSUE THREAD

**Issue by evan-brass** [fortanix/rust-mbedtls#282]
When I try to compile a Rust project that uses rust-mbedtls on my Mac I get the following error:
```
Undefined symbols for architecture arm64:
            "forward_mbedtls_calloc_c22ad3067e3bd134", referenced from:
                mbedtls::x509::certificate::_$LT$impl$u20$mbedtls..alloc..Box$LT$mbedtls..x509..certificate..Certificate$GT$$GT$::init::h451bf3c6d57f397e in libmbedtls-6df02c00bde7adfb.rlib(mbedtls-6df02c00bde7adfb.mbedtls.9ee9e34b-cgu.1.rcgu.o)
            "forward_mbedtls_free_c22ad3067e3bd134", referenced from:
                _$LT$mbedtls..alloc..Box$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$::drop::h0fd63a8ad66a1399 in libmbedtls-6df02c00bde7adfb.rlib(mbedtls-6df02c00bde7adfb.mbedtls.9ee9e34b-cgu.1.rcgu.o)
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

If I remove both of the `\u{1}` from alloc.rs then it compiles fine.  What's the purpose of putting this control character into the link_name and is there a work around or option I should be setting / passing?
https://github.com/fortanix/rust-mbedtls/blob/c5c69774692469ce839a7ab17fecb2425941d1c0/mbedtls/src/alloc.rs#L18-L20

**Comment by Taowyoo** [comment]
As far as I know, the `\u{1}` is used to force clang to not mangle the function.
This should be removed on condition to fix the compilation on Mac.

It would be very helpful if you could create a PR for adding a CI build on mac.

**Comment by Taowyoo** [comment]
Should be fixed by https://github.com/fortanix/rust-mbedtls/pull/276
Please reopen this issue if it still fails
