### ISSUE TITLE
Certificate from_pem_multiple error

### ISSUE THREAD

**Issue by vcxk** [fortanix/rust-mbedtls#319]
thread 'main' panicked at 'client certs parse fail HighLevel(X509FeatureUnavailable)'

-----BEGIN CERTIFICATE-----
MIIB3zCCAYSgAwIBAgIKJFwUdPePbaFocTAKBggqhkjOPQQDAjBHMRkwFwYDVQQK
DBBTdW5TcGVjIEFsbGlhbmNlMR4wHAYDVQQDDBVUZXN0IElFRUUgMjAzMC41IFJv
b3QxCjAIBgNVBAUTATEwIBcNMjMwNTEwMTg0MzIwWhgPOTk5OTEyMzEyMzU5NTla
MAAwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAR7J6F+m0QnYxtWB6/GZLvsDCK7
FXId+NYzoyByeFEImrIyh58+y/O22c+ddK+b4F2ibjLMWlKtNKJb0GIwDgYxo4Gc
MIGZMBMGA1UdIwQMMAqACE6/JuMvfQMeMA4GA1UdDwEB/wQEAwIDiDA2BgNVHSAB
Af8ELDAqMAwGCisGAQQBgr4cAQEwDAYKKwYBBAGCvhwCATAMBgorBgEEAYK+HAIE
MDoGA1UdEQEB/wQwMC6gLAYIKwYBBQUHCASgIDAeBgkrBgEEAYO+CwEEETkwMDAw
MDAwMDAwMDAwMDAxMAoGCCqGSM49BAMCA0kAMEYCIQDCKk4EUhhRIWY4ZoqNYBAf
s5MMlHWMPlvNKcDbksbmNAIhAJ01v0/yLlSjo/c7Qz8Tc6SwOmalQDZgFnav0KOA
Z42H
-----END CERTIFICATE-----

**Comment by Taowyoo** [comment]
I assume you are using `master` branch.
From `openssl` , some **critical** extensions in your certificate contains non-standard value/type or unsupported OIDs.
```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            24:5c:14:74:f7:8f:6d:a1:68:71
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: O = SunSpec Alliance, CN = Test IEEE 2030.5 Root, serialNumber = 1
        Validity
            Not Before: May 10 18:43:20 2023 GMT
            Not After : Dec 31 23:59:59 9999 GMT
        Subject: 
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:7b:27:a1:7e:9b:44:27:63:1b:56:07:af:c6:64:
                    bb:ec:0c:22:bb:15:72:1d:f8:d6:33:a3:20:72:78:
                    51:08:9a:b2:32:87:9f:3e:cb:f3:b6:d9:cf:9d:74:
                    af:9b:e0:5d:a2:6e:32:cc:5a:52:ad:34:a2:5b:d0:
                    62:30:0e:06:31
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Authority Key Identifier: 
                keyid:4E:BF:26:E3:2F:7D:03:1E

            X509v3 Key Usage: critical
                Digital Signature, Key Agreement
            X509v3 Certificate Policies: critical
                Policy: 1.3.6.1.4.1.40732.1.1
                Policy: 1.3.6.1.4.1.40732.2.1
                Policy: 1.3.6.1.4.1.40732.2.4

            X509v3 Subject Alternative Name: critical
                othername:<unsupported>
    Signature Algorithm: ecdsa-with-SHA256
         30:46:02:21:00:c2:2a:4e:04:52:18:51:21:66:38:66:8a:8d:
         60:10:1f:b3:93:0c:94:75:8c:3e:5b:cd:29:c0:db:92:c6:e6:
         34:02:21:00:9d:35:bf:4f:f2:2e:54:a3:a3:f7:3b:43:3f:13:
         73:a4:b0:3a:66:a5:40:36:60:16:76:af:d0:a3:80:67:8d:87
```

So `mbedtls` failed to parse them ( custom OIDs in Certificate Policies , custom ASN1 type in SAN). Note, when parsing critical extension, `mbedtls` only support standard extensions and types defined in RFC.

So if you want to use `mbedtls` to parse such certificate , you need to not mark extensions that contain custom ASN1 type or OID as `critical`.
Then you need to use `verify_with_callback` to do read and verify your custom value in extension manually.
