### ISSUE TITLE
Check to set `CMAKE_TRY_COMPILE_TARGET_TYPE` too restrictive

### ISSUE THREAD

**Issue by MasterAwesome** [fortanix/rust-mbedtls#355]
https://github.com/fortanix/rust-mbedtls/blob/4ff64a0b5f53d7b8b65f2a002f907852b123f85a/mbedtls-sys/build/cmake.rs#L35-L42

Targets don't necessarily end with `none-eabi` for example, if I wanted to compile for `aarch64-unknown-none` using `CFLAGS='-I <my_system_headers>' CC=clang cargo b --target aarch64-unknown-none` this fails. I think this must be configurable instead.

Removing this check, for the same command above allows me to run `mbedtls` code on baremetal aarch64.

**Comment by Taowyoo** [comment]
What solution you prefer? Make it configurable through env var?

Or could you create a PR for fixing this?
