### ISSUE TITLE
Docs on docs.rs are broken.

### ISSUE THREAD

**Issue by xfbs** [fortanix/rust-mbedtls#69]
I can't view the documentation. Can someone look into it?

<img width="1165" alt="Screenshot 2019-10-15 at 00 03 29" src="https://user-images.githubusercontent.com/786420/66786030-44267700-eedf-11e9-8862-f561174e4d40.png">

**Comment by jack-fortanix** [comment]
I think this is related to https://github.com/fortanix/rust-mbedtls/issues/5#issuecomment-539748449 - right now this crate is broken with nightlies after July 1st or so.
